server:
  port: 8080
  servlet:
    context-path: /egov

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
      maximum-pool-size: 50
  jta:
    enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB